name:  Prueba num 1

on:
  push:
    branches:
      - main

jobs:
  decir_hola:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo"
        Name: Enviar Peticion
        run: curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' -H 'content-type: application/json' -d $'{"nombre": "Daniel_GB"}'